In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import pandas as pd
import numpy as np
import keras
import cv2 as cv

In [0]:
df=pd.read_csv('/content/drive/My Drive/MOVIE POSTER CHALLENGE/movie_poster.csv')

In [19]:
print(df)
print((len(df)))

            tid  ... romance
0     tt0120737  ...   False
1     tt0167260  ...   False
2     tt0167261  ...   False
3     tt0169102  ...   False
4     tt0211915  ...    True
...         ...  ...     ...
2450  tt1692486  ...   False
2451  tt1695360  ...   False
2452  tt1696202  ...   False
2453  tt1699202  ...   False
2454  tt1699513  ...   False

[2455 rows x 9 columns]
2455


In [0]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size=0.2)

In [0]:
dfY_train=train.drop(columns=['tid','title','url','image_url','year'])
dfY_train=dfY_train.astype(int)
dfY_test=test.drop(columns=['tid','title','url','image_url','year'])
dfY_test=dfY_test.astype(int)

In [22]:
print(dfY_train.head())
print(dfY_test.head())

      action  scifi  drama  romance
2135       1      0      1        0
609        0      0      1        0
1230       0      0      1        1
455        1      0      0        0
695        1      0      0        0
      action  scifi  drama  romance
842        1      0      0        0
234        0      0      1        0
2448       1      0      0        0
1028       0      0      1        0
2199       0      0      1        0


In [23]:
dfX_train=train['tid']
X_train=[]
Y_train=[]
for tid in range(len(dfX_train)):
 try:
  path='/content/drive/My Drive/MOVIE POSTER CHALLENGE/posters/'+str(dfX_train.iloc[tid])+'.jpg'
  img=cv.imread(path)
  img=cv.resize(img,(100,100))
  img=img/255
  if(tid%100==0):
   print(tid)
  X_train.append(img)
  Y_train.append(dfY_train.iloc[tid])
 except: pass

dfX_test=test['tid']
X_test=[]
Y_test=[]
for tid in range(len(dfX_test)):
 try:
  path='/content/drive/My Drive/MOVIE POSTER CHALLENGE/posters/'+str(dfX_test.iloc[tid])+'.jpg'
  img=cv.imread(path)
  img=cv.resize(img,(100,100))
  img=img/255
  if(tid%100==0):
   print(tid)
  X_test.append(img)
  Y_test.append(dfY_test.iloc[tid])
 except: pass

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
0
100
200
300
400


In [24]:
#Y_train=Y_train.drop(columns=['tid'])
Y_train=np.array(Y_train)
print(Y_train)
Y_test=np.array(Y_test)
print(Y_test)

[[1 0 1 0]
 [0 0 1 0]
 [0 0 1 1]
 ...
 [1 0 0 0]
 [0 0 1 0]
 [1 1 0 0]]
[[1 0 0 0]
 [0 0 1 0]
 [1 0 0 0]
 ...
 [0 0 1 0]
 [1 0 1 0]
 [0 1 1 0]]


In [25]:
X_train=np.array(X_train)
print(X_train.shape)
print(Y_train.shape)
X_test=np.array(X_test)
print(X_test.shape)
print(Y_test.shape)

(1947, 100, 100, 3)
(1947, 4)
(489, 100, 100, 3)
(489, 4)


In [0]:
from keras.models import Model,Sequential
from keras.layers import Dense,Activation, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization,Input

In [0]:
 model=Sequential()
 #img=Input(shape=(96,96,3),dtype='float32')
 model.add(Conv2D(16, kernel_size=(3, 3), activation='relu'))
 model.add(Conv2D(16, (3, 3), activation='relu'))
 model.add(MaxPooling2D(pool_size=(2, 2)))
 model.add(Dropout(0.4))

 model.add(Conv2D(16, kernel_size=(3, 3), activation='relu'))
 model.add(Conv2D(16, (5, 5), activation='relu'))
 model.add(MaxPooling2D(pool_size=(2, 2)))
 model.add(Dropout(0.4))

 model.add(Flatten())
 model.add(Dense(64, activation='relu'))
 model.add(Dropout(0.6))
 model.add(Dense(4,activation='sigmoid'))

In [0]:
model.compile(loss='binary_crossentropy',optimizer=keras.optimizers.Adam(),metrics=['accuracy'])

In [43]:
model.fit((X_train),Y_train , batch_size=32,validation_data=(X_test,Y_test), epochs=30,class_weight='auto')

Train on 1947 samples, validate on 489 samples
Epoch 1/30
1947/1947 [==============================] - 1s 460us/step - loss: 0.3314 - acc: 0.8469 - val_loss: 0.5465 - val_acc: 0.7873
Epoch 2/30
1947/1947 [==============================] - 1s 432us/step - loss: 0.3106 - acc: 0.8530 - val_loss: 0.5822 - val_acc: 0.7837
Epoch 3/30
1947/1947 [==============================] - 1s 428us/step - loss: 0.3049 - acc: 0.8576 - val_loss: 0.5969 - val_acc: 0.7914
Epoch 4/30
1947/1947 [==============================] - 1s 438us/step - loss: 0.3065 - acc: 0.8579 - val_loss: 0.5852 - val_acc: 0.7837
Epoch 5/30
1947/1947 [==============================] - 1s 438us/step - loss: 0.3100 - acc: 0.8604 - val_loss: 0.5809 - val_acc: 0.7776
Epoch 6/30
1947/1947 [==============================] - 1s 435us/step - loss: 0.2902 - acc: 0.8611 - val_loss: 0.5558 - val_acc: 0.7817
Epoch 7/30
1947/1947 [==============================] - 1s 430us/step - loss: 0.2838 - acc: 0.8731 - val_loss: 0.6371 - val_acc: 0.7827
E

In [37]:
loss,acc=model.evaluate(X_test,Y_test)

print("Loss=",loss)
print("Accuracy=",acc)

489/489 [==============================] - 0s 199us/step
Loss= 0.5759162306176129
Accuracy= 0.7837423314102344


In [44]:
overclockwise='tt1642359'
amazingspidey='tt0948470'
solomonkane='tt0970452'
tintin='tt0983193'
bekushiru='tt0970472'
justiceleague='tt0974015'
bountyhunter='tt1038919'
path='/content/drive/My Drive/MOVIE POSTER CHALLENGE/posters/'+bountyhunter+'.jpg'
img=cv.imread(path)
img=cv.resize(img,(100,100))
img=img/255
test=[]
test.append(img)
test=np.array(test)
print(model.predict(test))

[[0.92872304 0.13080809 0.00360531 0.29286918]]
